### PR TITLE
Remove `flags` from `calyx` stage

### LINKED ISSUE #2327: [fud2] Remove `flags` argument from `calyx` stage
The calyx stage has both `flags` and `args` which seem to be doing the same thing. Also, `flags` defaults to `-p none` which is a bad default to use with the compiler.

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes #2327.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Looks like Cider uses this execution path in `fud2`. @EclecticGriffin what's the difference between `flags` and `args` in the `calyx` state and why does cider need the latter?

**Comment by EclecticGriffin** [comment]
Oh this was a hack since Cider wants to use a different default for the passes, i.e not lower things automatically, than other flows do. This was the easiest way I could figure to do it at the time without breaking existing things

**Comment by rachitnigam** [comment]
Hm, maybe we need to separate out the `calyx` stage's options to explicitly differentiate between pass specifications and other options (and throw errors if passes are provided as an input to the options)?

**Comment by rachitnigam** [comment]
Subsumed by #2334

**Pull request closed without merging**
