### PR TITLE
Promote if branches that don't have else stmts 

### PR DESCRIPTION
**Pull request by calebmkim**
Title

### CODE REVIEW

**Comment by rachitnigam** [comment]
@calebmkim are we planning to merge this?

**Comment by calebmkim** [comment]
Yeah; I might want to add a parameter flag about promoting `if` statements though. Unless you think it should be separate PRs.

**Comment by rachitnigam** [comment]
Do you mean a flag that sets the threshold for upgrading imbalanced branches or a flag to promote them at all? If we have the former, we don't need another flag I think.

**Comment by rachitnigam** [comment]
This will be affected by #1827

**Comment by rachitnigam** [comment]
@calebmkim ready to merge?

**Comment by calebmkim** [comment]
Yep (I meant to do this last week after tests passed but forgot)

**Pull request merged**
