### PR TITLE
new dynamic ohe branch due to weird git stuff

### PR DESCRIPTION
**Pull request by parthsarkar17**
Implements changes suggested in Tdcc ohe (PR #2087). Refactors `realize_schedule` and integrates with new changes to main. Adds correctness and snapshot tests.

### CODE REVIEW

**Comment by rachitnigam** [comment]
@parthsarkar17 what kind of weirdness are you running into with Github CI?

**Comment by parthsarkar17** [comment]
I don't think it was an issue with CI. It was more of a merge conflict that was causing me a little grief. I tried merging into the original branch, but I kept running into issues, and I figured it would be easier to just copy the code onto a new branch off of main. These were the merge issues that @ayakayorihiro was speaking about in #2087. Not the best solution, but it was a bit faster.

**Review by calebmkim — COMMENTED** [review]
One tiny comment on testing-- otherwise I would say you can merge. 

There are a couple code style suggestions-- (mainly one about factoring out querying a one hot FSM into a function). But I wouldn't say it's necessary for a merge.

**Comment by calebmkim** [comment]
Awesome, this all looks good to me-- I say merge when you're ready. 

As an aside: eventually we need a more sustainable way to test these new FSM optimizations once we add more and more different splits/encodings of FSMs. We can discuss this better.

**Pull request merged**
