### PR TITLE
Update `.expect` interface

### PR DESCRIPTION
**Pull request by csziklai**
This PR makes progress towards #2170. It applies the new expect interface to round robin and strict queues only. These queues call `queue_callcs`, which has the updated code, instead of `queue_call`. Additionally, code for the oracles had to be updated, in particular the method `operate_queue()`.  The value 10000 is given to pushes, and the value 20000 for errors generated from underflow or overflow. The next step is applying the changes across all queues.

### CODE REVIEW

**Comment by csziklai** [comment]
I think the reason it's failing is because I branched off a branch that I already deleted (hence the long list of commits). I would have branched off of main but there was some weird behavior that I've since resolved. I'm not sure what the best way to handle this error.

**Comment by anshumanmohan** [comment]
Hmm yeah something is a bit fishy. The "changed files" tab looks mostly fine to me (even that has some stray .md work of yours from another PR). Maybe the best way forward is the silliest one?
- Copy all the files that you changed, in their entirety, and have them around locally. The "files changed" tab is your friend when it comes to finding which files to copy in their entirety.
- Close this PR and delete this branch.
- Checkout the main branch. `git pull`. `cargo build`. Make sure `runt -x cocotb` passes. Since we believe that `main` is correct, running this `runt` test will ensure that your computer is not the problem.
- Make a new branch.
- Paste your locally saved versions of the relevant files.
- Make sure `runt -x cocotb` still passes.

The con of course is that your incremental progress all gets compressed into one magical commit where you figured everything out. Not the biggest disaster in the world

**Review by anshumanmohan — CHANGES_REQUESTED** [review]
Please see comment

**Comment by anshumanmohan** [comment]
From your screenshot, it looks to me like these failures are because of uninstalled Calyx frontends. What does that mean? Well when you installed Calyx (like [so](https://docs.calyxir.org/#installing-the-command-line-driver)), you got some warnings from `fud check` about uninstalled tools. That's alright, no problem. I think these failures are local and would go away on a machine where all the `fud` tools were installed.

Some of these may also go away if you do `cargo build` after doing `git pull` on the main branch. 

New proposal: run the `runt` command, and simply note down how many failures you are causing. Maybe have Adrian or some other grad student in the lab (Griffin?) take a look at the list of failures, just to make sure that the failures are not critical. For example a failure in a `core` tests would be bad. So just get a green light from someone that the failures look like they're "just local".

Then, as you branch off and do your development, make sure that you are not causing any new things to break! How does that sound?

**Pull request closed without merging**
