### PR TITLE
Disable rounding for float conversion

### LINKED ISSUE #2336: Floating-point conversion error
There is a bug in the tests provided by https://github.com/calyxir/calyx/pull/2318.

[tests/correctness/ieee754-float/parse-and-print.futil.data](https://github.com/calyxir/calyx/pull/2318/files#diff-e4146a309a9876672f57eb53e44b7c9042a5a222c53eb6894ff48df0c6a950fd) provides the input value `15.1239`. However, at the end of the test, the value has changed to `15.12` in [tests/correctness/ieee754-float/parse-and-print.expect](https://github.com/calyxir/calyx/pull/2318/files#diff-5d85d972c197f71bd7796802102b6e470a03f2b8cf64f277a0f8208dffcaca99).

This is even though a 32-bit IEEE float should be able to represent `15.1239`. So there appears to be a bug, most likely in how the data is converted back after the simulation.

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes #2336. Currently running into the same problem as https://github.com/calyxir/calyx/pull/2335#issue-2636162273

@ekiwi how did you fix it on the Rust side?

### CODE REVIEW

**Comment by rachitnigam** [comment]
I am currently getting this output:
```
{
  "inp": [
    15.123900413513184
  ],
  "out": [
    15.123900413513184,
    0.5600000023841858
  ]
}
```

Which might be fine since that is the closest representable number from the input files? Thoughts @ekiwi?

**Comment by ekiwi** [comment]
> how did you fix it on the Rust side?

I fixed it by printing out the f32 instead of the f64

**Comment by ekiwi** [comment]
Stackoverflow seems to suggest using numpy to work with single precision float. However, it is still unclear to me whether numpy can actually print 32-bit floats.

https://stackoverflow.com/questions/2232362/correct-way-to-emulate-single-precision-floating-point-in-python

**Review by ekiwi — APPROVED** [review]
Awesome. Thanks! :shipit:

**Pull request merged**
