### PR TITLE
Add playground config validation script and CI

### LINKED ISSUE #1737: Re-enable playground github workflow
The playground workflow [suddenly started failing](https://github.com/cucapra/calyx/actions/runs/6463043645/job/17546014541). A likely cause is the underlying ubuntu container for GH actions being updated and causing one of the dependencies to fail.

### PR DESCRIPTION
**Pull request by YJDoc2**
closes #1737 
ref : https://github.com/calyxir/calyx/issues/1737#issuecomment-1986905609

Sorry it took a bit of time to get this up, got busy in other things...

This adds a node script which will validate that 
1. All passes listed in the passes.json are valid (cross checking with calyx pass-help o/p)
2. all example files that are in config.json are actually present

Currently parked the CI in rust.yaml, as I figured it would be better to run on each push, can move to other yaml as per suggestions.

Also instead of checking with master, the files are checked at local level, so that addition of new file or removal of existing file is correctly detected. I can also add a step to post a comment on PR if the validation fails, but might be overkill.

Once suggested changes are added, will remove the non existent passes and example files so the CI passes. Example of failing CI https://github.com/YJDoc2/calyx/actions/runs/8331868876/job/22799692081

@sampsyo please take a look, thanks :)

### CODE REVIEW

**Comment by YJDoc2** [comment]
Hey also, if similar to last time, you are not getting the `approve and run` button for PR , and checks are pending, it might be because the CI are on push only, and thus run in my fork, but not on PR here. Most other PRs I checked  are from this repo to this repo, so their CI might be working properly. When I filter in actions for event pull_request only fud2 CI is there, others do not have any runs, so this might  be the cause for pending checks.

**Comment by rachitnigam** [comment]
Awesome, thanks @YJDoc2!

**Comment by YJDoc2** [comment]
Hey, So I'll remove the missing stuff / passes so the CI will pass ; I'm disabling auto merge so that you can suggest if you want a specific pass / example added, and it won't just get merge automatically.

**Comment by YJDoc2** [comment]
Not entirely sure why the previous commits failed, but the latest main merge is succeeding CI. Given that the demo data validation CI is passing (which is added in this PR) , and I haven't actually changed any core code, only the example config data in web demo ; can the previous failures be ignored and this merged? @rachitnigam

**Comment by rachitnigam** [comment]
Yeah, it was a dockerfile failure.

**Pull request merged**
