### PR TITLE
Separate Inference and Promotion into Separate Passes

### PR DESCRIPTION
**Pull request by calebmkim**
This is the first step of the progress described in [here](https://github.com/calyxir/calyx/issues/1429#issuecomment-1910898327). 

Apologies for the really big PR, but a lot of it is just moving around code and slightly changing tests. 

The main new thing is the [fixup_timing](https://github.com/calyxir/calyx/blob/c8ce3a8ab97ddf8fd2b155f4d73341181b3b9e32/calyx-opt/src/analysis/inference_analysis.rs#L486) function. Suppose component B instantiates component A. Suppose also that we infer component's A's latency, and use that to infer the latency of B. If we decide not to promote A, then we can the inference information in B is no longer valid. This `fixup_timing` function should account for that. I wrote the function so that it can also (hopefully) be applied to compaction when we need to re-infer components after we compact them. There are tests for this behavior it [here](https://github.com/calyxir/calyx/blob/c8ce3a8ab97ddf8fd2b155f4d73341181b3b9e32/tests/passes/static-promotion/fixup-necessary.futil#L1) and [here](https://github.com/calyxir/calyx/blob/c8ce3a8ab97ddf8fd2b155f4d73341181b3b9e32/tests/correctness/static-control/fixup-necessary.futil#L1)

### CODE REVIEW

**Comment by rachitnigam** [comment]
Awesome! BTW, the previous implementation of this kind of "fixup" logic is in [`WithStatic`](https://docs.rs/calyx-opt/latest/calyx_opt/analysis/trait.WithStatic.html). We can remove it in a follow-up PR as we start getting rid of `@static` (#1429).

**Comment by calebmkim** [comment]
> BTW, the previous implementation of this kind of "fixup" logic is in [WithStatic](https://docs.rs/calyx-opt/latest/calyx_opt/analysis/trait.WithStatic.html). 

Yeah, I actually use [WithStatic](https://docs.rs/calyx-opt/latest/calyx_opt/analysis/trait.WithStatic.html) already in the FixUp (I just changed the `@static` keyword to `@promote_static`). It's just that the FixUp also needed to remove and then re-infer the latencies of groups as well.

**Comment by sampsyo** [comment]
All sounds good, and the implementation looks great! As we discussed synchronously, this "fixup" behavior for backing out some cross-component inference seems like the right thing.

The one thing I realized I don't completely understand about this is: I think the rule is (using your scenario above) we need to remove inferred latencies from B *if B writes to A*. I don't quite understand why writes are important in particular… I guess I would have expected the documentation for the function to say, like, "uses" or something. Is it just because any use involves a write to some input port (at least to the `go` port)? And merely reading from ports does not actually activate the control of the component?

**Comment by calebmkim** [comment]
> I don't quite understand why writes are important in particular… I guess I would have expected the documentation for the function to say, like, "uses" or something. Is it just because any use involves a write to some input port (at least to the go port)? And merely reading from ports does not actually activate the control of the component?

Yeah; in fact, I think my implementation was a bit imprecise. A more precise rule could be something like: we need to remove inferred latencies from B if _B writes to the go port of A_. Just reading from `A` shouldn't affect the component's latency.

**Comment by sampsyo** [comment]
Makes sense; thanks for clarifying! This level of precision seems fine to leave to future work. :smiley:

**Comment by rachitnigam** [comment]
Does this fix https://github.com/calyxir/calyx/issues/1852?

**Comment by calebmkim** [comment]
No, but I have a PR that's almost ready that will fix it.

**Comment by calebmkim** [comment]
I'll merge this (I have more PRs coming, so I can adress any changes in those PRs as well).

**Pull request merged**
