### PR TITLE
Docs: correct command to list passes

### PR DESCRIPTION
**Pull request by anshumanmohan**
The [docs](https://docs.calyxir.org/compiler.html#controlling-passes) tell you to run 
```
cargo run -- --list-passes
```
from the root of the repository in order to see a list of Calyx passes. In reality I have found the command is 
```
calyx --list-passes
```
and it does not need to be run from the root. 

This PR changes the docs to reflect this. Please let me know if I've somehow gotten it wrong, or if additional context is needed at that point in the docs.

### CODE REVIEW

**Comment by rachitnigam** [comment]
The command has changed to "calyx pass-help" on the latest build. I didnt realize that we still have "--list-passes"

**Comment by anshumanmohan** [comment]
Hmm, confused. I just pulled main, did `cargo clean` and `cargo build`, and I still find that `calyx --pass-help` is unrecognized and `calyx --list-passes` works? I'm missing something!

**Comment by rachitnigam** [comment]
pass-help is a subcommand not a flag

**Comment by anshumanmohan** [comment]
Gotcha, I have changed the docs again to reflect this. I haven't actually removed the power to run 
```
calyx --list-passes
```
I have also allowed the list-pass option to appear in the menu of possible flags when one runs 
```
calyx --help
```

**Pull request merged**
