### PR TITLE
Remove duplicate ops from lib.rs.

### PR DESCRIPTION
**Pull request by jku20**
This PR removes ops from `lib.rs` which are duplicated in Rhai scripts.

### CODE REVIEW

**Comment by jku20** [comment]
@nathanielnrn I think you're code is the only bit of rust code which is still needed. I've tried to port it over but it seems to fail tests, but I suspect this is because it simply has a different output! 

Can you verify the behavior in this commit is what's intended? My `sed` is not good enough to confidently figure out what the addition does and reason about it myself.

**Comment by jku20** [comment]
So, just removed the new `sed` command. I think (in part based on the comment and what it was doing) it was just kind of cleaning up a file to make it a bit more readable.

I don't think that codepath was being taken in the current tests (which I think go through `Rhai` entirely right now). 

So yeah, I'm of mind to just go ahead and remove the `lib.rs` now!

**Comment by rachitnigam** [comment]
@jku20 are we planning to merge this? If not, what's blocking us?

**Comment by jku20** [comment]
Nothing's blocking this other than a review and me forgetting to ask someone for one.

**Comment by jku20** [comment]
Okay, so this is broken still because I think it will die if it compiles without "migrate_to_scripts" set. I think the course of action is to fix that and then just merge it (hopefully like this weekend or something like that).

**Comment by rachitnigam** [comment]
@jku20 can you say a bit more what this mean? I would like to get this merged.

**Comment by jku20** [comment]
Currently lib.rs defines build_driver which I removed. This means when migrate_to_scripts isn’t set, the fud2 doesn’t compile. The fix is as simple as removing the compile option and all the references to build_driver. I should really just do that today (haven’t gotten around to it because had a pretty hectic couple weeks).

**Comment by jku20** [comment]
Should be ready to be merged!

**Review by sampsyo — APPROVED** [review]
Looks perfect!! Thank you, @jku20!

**Pull request merged**
