### PR TITLE
[fud2] Experimental support for managing python environment

### PR DESCRIPTION
**Pull request by sgpthomas**
This is an experiment and I'm curious what folks think.

The main thing this PR does is to add an `env` subcommand that
1) initializes a python virtualenv
2) installs necessary python libraries
3) updates `fud2.toml` to point to the virtualenv python

The point of this is to simplify the user experience of getting fud2 up and running and eases the burden of having to manually deal with installing python packages into the right place (see #2263). However, I'm not sure if we want `fud2` to be in the business of managing python dependencies. The right place to solve this might actually be in documentation.

This feels very fud2 specific and so I've put this in the fud2 frontend rather than in `fud-core`. To accomplish this I implemented a method for extending the cli that `fud-core` provides. This takes advantage of `argh::DynamicSubCommand`. This works, but has the downside of not updating the `--help` screen. I might just be doing something wrong there, who knows.

### CODE REVIEW

**Comment by sgpthomas** [comment]
Realized I didn't need the dynamic subcommands. Normal subcommands sort of work. There is the downside though that if some user of `fud-core` doesn't want to extend the cli. there is this empty subcommand thats generated

**Comment by sgpthomas** [comment]
Just waiting on a review for this

**Comment by rachitnigam** [comment]
Does the help screen not show the new 'env' command?

**Comment by sgpthomas** [comment]
It shows up for me:
Screenshot 2024-10-19 at 3 17 16 PM

**Comment by sgpthomas** [comment]
For more context. The implementation has diverged from the original. I'm just using normal argh::Subcommands instead of the `DynamicSubCommand`. This means that we get help display, and adding subcommands is simpler. At the cost of having an "empty subcommand" if some user of `fud_core` doesn't add a command.

**Comment by rachitnigam** [comment]
That seems fine to me! Can you add some documentation about how this command works for docs.calyxir.org? Apart from that, LGTM!

**Comment by sgpthomas** [comment]
Added the docs, and slightly simplified the Cli Extention API, which also had the effect of not having the empty command appear if you're not using a Cli extension. Once I get the ok, I'll click the green button.

**Comment by rachitnigam** [comment]
LGTM!

**Pull request merged**
