### PR TITLE
Fix failing tests on `main` due to new Rust version

### PR DESCRIPTION
**Pull request by ethanuppal**
Uses interior mutability with a `RwLock` and `lazy_static!`.

### CODE REVIEW

**Comment by EclecticGriffin** [comment]
The use of `Box::leak` for the immutable read is causing this to deadlock since the lock believes there is always an outstanding read. Probably need to return a read guard instead of a reference, unfortunately.

**Comment by ethanuppal** [comment]
Thanks, no idea why I didn't think about that

**Comment by EclecticGriffin** [comment]
I'm in favor of merging this for the moment to get CI unbroken and considering more robust solutions later. Extra cloning won't hurt us in the short term, I hope.

**Comment by ethanuppal** [comment]
Yeah, the extra `clone`s are annoying, but also not the end of the world, and also very likely won't be a performance bottleneck.

**Comment by ethanuppal** [comment]
@rachitnigam

**Comment by rachitnigam** [comment]
I would trust @EclecticGriffin's advice on this over mine.

**Comment by ethanuppal** [comment]
Ok, I'm going to (1) add to the issue the list of places cloning was introduced and (2) start thinking about how we want to fix this for real. I'm thinking we might want to refactor the entire position table setup. Discussion in #2366.

**Pull request merged**
