### PR TITLE
Improve LSP error reporting

### PR DESCRIPTION
**Pull request by sgpthomas**
- [x] Actually run papercut, well-formed, and synthesis-papercut passes
- [x] support multiple errors in a single file
- [x] figure out what to do about primitive files that have no main component
- [x] Report parsing errors at reported location
- [x] handle errors that don't report location
- [x] add infrastructure for reporting warnings

### CODE REVIEW

**Comment by sgpthomas** [comment]
It's fun to flip through the error tests and see errors being reported.

https://github.com/calyxir/calyx/assets/3752122/949758e2-8a06-4e26-a1f5-9dd751d872af

**Comment by sampsyo** [comment]
Dang, this is awesome.

**Comment by rachitnigam** [comment]
@sgpthomas should we merge this?

**Comment by sgpthomas** [comment]
Yeah

**Comment by rachitnigam** [comment]
Push the big green button when ready!

**Pull request merged**
