### PR TITLE
Fix playground deployment

### PR DESCRIPTION
**Pull request by YJDoc2**
ref : https://github.com/calyxir/calyx/issues/1926#issuecomment-1971142702

This fixes the issues with current playground as well as fix the playground deployment CI to run on every main merge.
The CI run can be seen on my branch [here](https://github.com/YJDoc2/calyx/actions/runs/8114037990/job/22178759454) and the deployment can be seen [here](https://yjdoc2.github.io/calyx/) 

There are still some issues such as `compile empty` pass saying `Unknown pass: compile-empty. Run compiler with pass-help subcommand to view registered passes.` , but I have some other ideas to fix this, and feel that a separate PR to fix that would be better than to add those changes in this.

Also the deployment CI contains `workflow_dispatch` for testing, I'll remove it once rest of the changes are approved/ reviews addressed.

Also note that unlike before the `npm run start` will not auto re-compile wasm when rust source changes ; but doing a manual `npm run wasm-dev` will re-compile the wasm, and that will trigger reloading of vite dev server.

For local testing, 
1. make sure you have wasm-pack installed, 
2. remove `node_modules` dir if you have it in`web/` 
3. do npm ci in the web dir
4. run npm start

### CODE REVIEW

**Comment by YJDoc2** [comment]
@sampsyo May I ask you to take a look at this?

Also I think as I'm contributing first time to this repo, the CI must be approved to run.

Thanks :)

**Comment by sampsyo** [comment]
Wow; awesome!! Thank you for looking into this!

Something is a little weird with the CI on this PR—I don't have the usual button that appears to approve Actions runs for first-time contributors. All the Actions just say "Waiting for status to be reported." Not sure what's up with that—maybe if I push something to this branch, it'll trigger them properly. In any case, I'll test everything locally to see if I can make it work!

**Comment by sampsyo** [comment]
Wow; it totally works!! Wahoo! Awesome work on this. :tada:

CI weirdness aside, I'll remove that `workflow_dispatch` trigger and merge this now. I'll take responsibility for any Actions breakage that happens on main. That way, we can hopefully (a) get this working in the deployed site, and (b) continue iterating! Yay!!!

**Comment by sampsyo** [comment]
Hey, it [worked](https://play.calyxir.org)!! Wahoo!

**Comment by YJDoc2** [comment]
> Hey, it [worked](https://play.calyxir.org/)!! Wahoo!

Yay!

> Something is a little weird with the CI on this PR

I think when I opened this PR, there was a github incident regarding CI and branches in progress. Maybe that caused this particular PR's CI to be broken.

**Comment by sampsyo** [comment]
That makes sense!

**Pull request merged**
