### PR TITLE
Pass Reorder Option

### PR DESCRIPTION
**Pull request by calebmkim**
For the Calyx-Static evaluation, when we had to reorder schedule-compaction and cell-share, I would manually change the order of passes and then checkout a different commit. 

I added an option to make this easier: I'd like to know what people think of this option. (We don't have to merge this if people don't want). 

This PR adds a command line option to reorder passes. 
If you pass
```
cargo run *.futil -r pass1 -r pass2 -r pass3 -r pass4 
```
then it will still run all the passes run, but it will run the 4 passes you entered in the specified order (`pass1` then `pass2` then `pass3` etc). 

This is particularly useful because it lets you rearrange optimization passes. E.g., 
```
cargo run *.futil -p pre-opt -r pass1 -r pass2 -r pass3 -r pass4 
```
lets you run all of the `pre-opt` passes, but lets you rearrange the order in which you do this, instead of manually having to type in the exact order that you want.

### CODE REVIEW

**Comment by anshumanmohan** [comment]
Very nice, and I like that it maintains brevity because of your nice feature where the passes to be run are specified as usual, and this `-r` thing just places an order. Just occurs to be to ask you about two corner cases:
- What happens if the user requests an order that is known to be a terrible idea?
- What happens when the user specifies an order among passes that aren't slated to be run? 
 

I presume the answer to the first is that we can't help such a user and we just let it happen. For the second maybe a quick check is possible?

**Comment by rachitnigam** [comment]
> What happens if the user requests an order that is known to be a terrible idea

This a particularly good question because some passes have implicit dependencies or requirements (which should really be specified within the passes themselves: "no `with` statements exist", "all control is compacted" etc.)

**Comment by calebmkim** [comment]
After thinking about it, I think this "reordering" option leaves too much room for ambiguity. (For example, think about if we have `pass1 pass2 pass3 .... pass9` slated to run: does specifying `-r pass6 -r pass3` simply switch the order of the passes? Or does it insert `pass3` right after `pass6`? Or does it insert `pass6` right before `pass3`? )

I decided to switch to something better-defined, and more realistic for the types of tinkering I (and hopefully most people) want to do with pass orderings. An `insertion` option. 

`-i pass1:pass2` will maintain the exact same order, but insert `pass2` directly after `pass1` in the pipeline.  
- If either of `pass1` or `pass2` are not passes, then we will give an error (just as we would if we `-p pass1` was not an actual pass).  
- If either of `pass1` or `pass2` are passes but are not slated to run, then we issue a warning and ignore the option. 
- The insertions occur in the order they are specified (like `-p`). 
- If you specify a terrible order that violates dependencies, then that's your fault and you will get an error (like what would happen if you specify `-p pass2 -p pass1` and `pass2` depends on `pass1`).

**Comment by anshumanmohan** [comment]
Cool, makes sense! And it certainly sounds like you have found a use-case, albeit a niche one. So I'd say merge away!

**Pull request merged**
