### PR TITLE
[fud2] Rhai Plugins

### PR DESCRIPTION
**Pull request by sgpthomas**
After some discussion with @sampsyo, I've decided to push forward with the scripting language based plugin system for fud2. I've switched it to using [`rhai`](https://rhai.rs/) however, because it has more seamless integration with Rust. I support most of the `fud-core` interface at the moment, but it's not well-tested and the code could use some cleanup.

Some todos:
- [x] Decide if we want both `EmitSetup` and `EmitRcSetup` (we probably don't need both)
- [x] Infrastructure for telling fud where to find plugins
- [ ] Some kind of testing
- [ ] Maybe some migration of existing ops into the plugin layer?
- [ ] If we want to ship plugins for functionality, how do we do this?

Referencing the old issue for the history: #2070

### CODE REVIEW

**Comment by sgpthomas** [comment]
One quick note. This represents a first iteration of a plugin system. Hopefully this will lay the groundwork for working on a DSL for a nicer interface for defining fud2 operations.

**Comment by sgpthomas** [comment]
My current solution causes tests to fail because the Emitter needs to have a 'static lifetime to be able to be used in Rhai. This is not ideal, and would like to find a way to restore the lifetimes to what they were.

**Review by sampsyo — COMMENTED** [review]
Wow, this is AWESOME! Really awesome work on this. I think the scripts themselves look great, the Rhai/Rust bindings pretty much could not be simpler (you just provide a `Clone` value to expose it to the script world), and the setup for loading plugins looks just great!!

Here's one EXCEEDINGLY minor thing: I wonder if we should rename the concept (and the Rust module) from "plugins" to "scripts"? Or, really, to separate the names for the two concepts: scripts are the general way to write fud2 functionality in Rhai, and plugins are when you configure fud2 to load extra scripts from files. That way, we semiotically allow for the existence of non-plugin scripts, i.e., built-in functionality written in Rhai.

Of course, a mechanism for built-in scripts is still pending.

And finally: this may be totally ridiculous, but it is a tiny bit sad to have the Rc/RefCell business and the `Vec<u8>` buffering contaminate even the core layer. This may be inevitable, and I probably traversed exactly the same path as you when looking for a straightforward solution---I even encountered https://github.com/rhaiscript/rhai/issues/882 when searching for other people dealing with this in Rhai! Small world, I guess.

Anyway, here is one idea for an alternative, even sillier solution that has a totally different downside. We create a new, temporary Emitter for every call into a script function. This temporary emitter will do buffering, and then, after the cal to the Rhai function, we just write that buffer to the "real" emitter's output stream.

In slight more detail: An emitter has only 3 fields: the output stream, the config, and the destination path. The latter two are `Clone`, so we can just do that for those. For the output buffer, we make the temporary emitter have a `Box<Vec<u8>>` for its output stream. We add a method like `bufferred` that creates one of these temporary emitters from an existing one, and another method `unbuffer` or whatever that consumes it and writes the buffered bytes to the stream.

I know this incurs a bunch of overhead on every call into the script. That's the downside, I guess. But one thing it might enable in the future is more reuse of a single such object for the entire lifetime of the Rhai engine... only one configuration will ever be provided, for example. So we could think separately about how to make the static aspects "eternal."

Is this crazy? I don't know why I just aesthetically like the idea of letting Rust-implemented functionality continue to "stream" and avoid Rc... it's not worth paying a lot of attention to these kind of aesthetics, but sometimes I just can help myself. Anyway, I'd be very interested in your thoughts!

**Comment by sampsyo** [comment]
Here's a quick n' dirty demonstration of the "local buffering" strategy I mentioned above, just to check that it's not *completely* unworkable: https://github.com/calyxir/calyx/compare/main...buf-emitter

**Comment by sgpthomas** [comment]
I think that the plugin/script distinction makes sense and is wise. Yeah the `Rc` nonsense is not ideal. I prefer the separate Emitter pattern. Thanks for mocking that up.

**Comment by sgpthomas** [comment]
I implemented the suggested changes. I think this is now complete enough for merging. I think we can postpone migrating existing ops and dealing with shipping scripts to a later PR. Let me know if the structure/naming etc looks good.

**Review by sampsyo — APPROVED** [review]
Wonderful! This absolutely kicks ass. Great work breaking this down into a few submodules here; that makes a lot of sense too.

**Pull request merged**
