### PR TITLE
Add bypass_reg and skid_buffer to core

### PR DESCRIPTION
**Pull request by andrewb1999**
Subsumes #2030. Both of these primitives essentially do the same thing but have slightly different interfaces and behavior in some circumstances. I think we will eventually move to just using skid_buffer which is the more standard interface, but bypass_reg is what we use in our code right now and I don't really want to mess with that for now.

### CODE REVIEW

**Comment by andrewb1999** [comment]
@EclecticGriffin I understand why these test cases fail the interpreter. Is there a place I can put these test cases such that the interpreter won't be called on them and we just test in simulation for now?

**Comment by EclecticGriffin** [comment]
> @EclecticGriffin I understand why these test cases fail the interpreter. Is there a place I can put these test cases such that the interpreter won't be called on them and we just test in simulation for now?

Yeah if you update the runt command in the rust.yaml workflow! All you need to do is add the name of the tests to the `-x` regex

**Comment by EclecticGriffin** [comment]
Here's the line to edit: https://github.com/calyxir/calyx/blob/main/.github%2Fworkflows%2Frust.yml#L126

**Comment by andrewb1999** [comment]
> Yeah if you update the runt command in the rust.yaml workflow! All you need to do is add the name of the tests to the `-x` regex

Thanks! I think I figured it out, just need to make sure it passes CI now.

**Comment by rachitnigam** [comment]
I would recommend adding skip files instead

**Comment by andrewb1999** [comment]
> I would recommend adding skip files instead. That way we will eventually add them into the interpreter too.

How do I do that?

**Comment by rachitnigam** [comment]
Wherever the test generates the .expect file, you can instead place a .skip file of the same name.

The simplest way to do this is to save the error file and rename it to have the extension .skip. Bonus points if you empty out the file and remove the contents.

**Comment by andrewb1999** [comment]
> Wherever the test generates the .expect file, you can instead place a .skip file of the same name.
> 
> The simplest way to do this is to save the error file and rename it to have the extension .skip. Bonus points if you empty out the file and remove the contents.

Won't that just always skip the test? At least how it's setup right now it will run the test in simulation.

**Comment by andrewb1999** [comment]
Actually I just realized we can't run this test with the interpreter anyways because I wrote them using static control. There is probably a way to write them without static control but probably not worth figuring out right now.

**Comment by andrewb1999** [comment]
Alright passing CI now. Any comments or should I merge?

**Comment by rachitnigam** [comment]
One last one: could you add documentation about these primitives: https://docs.calyxir.org/libraries/core.html

(maybe a new heading called state elements)

feel free to merge after that.

**Comment by andrewb1999** [comment]
Alright I added documentation, going to go ahead and merge.

**Pull request merged**
