### PR TITLE
Installation instructions fix: Make runt.toml expect runt version 0.4.1 instead of 0.4.0.

### PR DESCRIPTION
**Pull request by nathanielnrn**
Fixes issue when following ['Getting Started'](https://docs.calyxir.org/#running-core-tests) requiring a manual version change in runt.toml. Could also be addressed in runt itself, but this is a bandaid fix for now.

### CODE REVIEW

**Comment by rachitnigam** [comment]
The tests seem to be failing with this change. Maybe we need to update the GitHub workflow files to install a newer version of runt?

**Comment by nathanielnrn** [comment]
Strange. The [docker file installs runt](https://github.com/cucapra/calyx/blob/master/Dockerfile#L61C5-L62C1) using
`cargo install runt --version $(grep ^ver runt.toml | awk '{print $3}' | tr -d '"')`
Which is 0.4.1 with this change.

Would a new image need to be pushed to ghcr? I remember in the past that was done manually by you @rachitnigam.

**Comment by rachitnigam** [comment]
A new version of the codebase has been released which means that the docker container `calyx:0.6.0` should be up soon. After its up, we need to bump the github workflow files to use it instead of `calyx:0.3.0` and that *should* work...

**Comment by nathanielnrn** [comment]
To get polybench working will need to merge this [calyx-evaluation PR](https://github.com/cucapra/calyx-evaluation/pull/16)

Also note that docker image 0.6.0 [does not have git intialized in /home/calyx](https://github.com/cucapra/calyx/issues/1714).

For compiler tests, I'm getting cocotb runt errors. Which also seem to be happening on master? Even on 0.4.0. Not sure if those are expected to fail due to some other work?

**Comment by rachitnigam** [comment]
The tests on `master` are passing. This might be an annoying issue to fix because of #1714. Not sure what is causing the problem but one option might be using the `$HOME` variable instead of hardcoding `/home/calyx` but can't be sure it'll work till we figure out what is causing the problem.

**Comment by nathanielnrn** [comment]
Failing compiler tests seem to be coming from stale
`tests/frontend/systolic/array-2.expect` and `tests/frontend/systolic/array-3.expect`
that are present in the docker container but not in the calyx repo. In `0.3.0` these are tracked and therefore removed when switch to latest commit. In `0.6.0` these are not tracked and so remain in the container. For now going to see if manually removing them solves things.

**Comment by sampsyo** [comment]
> Failing compiler tests seem to be coming from stale
> `tests/frontend/systolic/array-2.expect` and `tests/frontend/systolic/array-3.expect`
> that are present in the docker container but not in the calyx repo. In `0.3.0` these are tracked and therefore removed when switching to latest commit. In `0.6.0` these are not tracked and so remain in the container.

What a mess! Do we know why these files exist in the `0.6.0` container, despite not being in the repository? If some command is putting them there when the image is being built, it seems like we should probably just stop that from happening…

I also mentioned in https://github.com/cucapra/calyx/issues/1714#issuecomment-1711985357 that it seems to me like lots of this headache arises from our current CI approach, which ends up with two different versions of Calyx co-existing and potentially confusing each other. Sticking to just one (either just from the container, or just from git) could help make this stuff less surprising.

**Comment by rachitnigam** [comment]
Let's try this again after #1824

**Pull request closed without merging**
